#!/Users/geoffreylitt/.rubies/ruby-2.6.3/bin/ruby
# conditional output to html and pdf, by interpreting a special class name on divs in markdown

# to use in a markdown doc:
 
#  Here is some normal text.
#  <div class="html-only">Some text for only html</div>
#  <div class="pdf-only">Some text for only pdf</div>

require "paru/filter"

Paru::Filter.run do 
    with "Div.html-only" do |div|
      div.inner_markdown = "" unless metadata["format"] == "html" 
    end

    with "Div.pdf-only" do |div|
      div.inner_markdown = "" unless metadata["format"] == "pdf" 
    end
end
